alias gco="git checkout"
alias gcom="git checkout master"
alias gst="git status"
alias gc="git commit -a"
alias gd="git diff"
alias gb="git branch"
alias gp="git push"
alias gl="git log"
alias gtree="git log --graph --all --format='%x09%C(cyan bold)%an%Creset%x09%C(yellow)%h%Creset %C(magenta reverse)%d%Creset %s'"
