syntax on
filetype on
filetype plugin on
filetype indent on
set backup

noremap  
noremap!  
noremap <BS> 
noremap! <BS> 
noremap <C-j> <Esc>
noremap! <C-j> <Esc>

set noswapfile
set backspace=indent,eol,start
set ruler
set showcmd
set showmode
set list      " show invisibility character
set listchars=tab:>^,extends:»,precedes:«
set laststatus=2

set tabstop=4 
set shiftwidth=4
set expandtab   " insert space when tab key pushed.
set smartindent " insert indent when move to new line.
set showmatch
set number      " show line number.
set cursorline  " highlight the screen line of the cursor.
set cursorcolumn
set title       " set terminal's title.

set wildmenu    " use complecation of command line.
set history=500 " number of commandlines to recommend.

set incsearch   " inclemental search
set hlsearch    " highlight search result.
set ignorecase  " ignore case in search patterns.
set smartcase   " If including big letter, disable ignore case.

set hidden      " don't unload buffer when it is abandoned

set fileencodings=utf-8,euc-jp,cp932,iso-2022-jp,default

set t_Co=256 " 256 color
syntax enable

"python's option
filetype plugin on
autocmd FileType python setl autoindent
autocmd FileType python setl expandtab tabstop=4 shiftwidth=4 softtabstop=4

"configuration of highlight
hi Comment ctermfg=lightblue

" dein setting ---------------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=~/.vim/.cache/dein/repos/github.com/Shougo/dein.vim

let s:dein_toml=expand('~/.vim/dein.toml')
let s:dein_toml_lazy=expand('~/.vim/dein_lazy.toml')

" Required:
if dein#load_state('~/.vim/.cache/dein')
  call dein#begin('~/.vim/.cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add('~/.vim/.cache/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here
   call dein#load_toml(s:dein_toml, {'lazy': 0})
   call dein#load_toml(s:dein_toml_lazy, {'lazy': 1})


  " You can specify revision/branch/tag.
  call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

  " Required:
  call dein#end()
  call dein#save_state()
endif

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
